# Dataset Loading

- Load the raw training text file

- Read the entire dataset into memory

- Inspect dataset size and preview content

In [56]:
with open("traindata.txt",'r',encoding='utf-8') as f:
       text=f.read()


In [57]:
print("The length of Data set:",len(text))

The length of Data set: 209192


In [58]:
print(text[:1000])

The Portrait of a Lady
A Photograph
“We’re Not Afraid to Die... if We
Can All Be Together”
Discovering Tut: the Saga
Continues
The Laburnum Top
The Voice of the Rain
The Ailing Planet: the Green
Movement’s Role
Childhood
The Adventure
Silk Road
Father to Son
Reprint 2025-26
Effective reading is receiving from others
their ideas and feelings.
Effective reading involves
 understanding the text
 talking about the text
 thinking about language
 working with words
 noticing form and patterns.
Reprint 2025-26
1. The Portrait of a Lady
Khushwant Singh
Notice these expressions in the text.
Infer their meaning from the context.
My grandmother, like everybody’s grandmother, was an old woman.
She had been old and wrinkled for the twenty years that I had known
her. People said that she had once been young and pretty and had
even had a husband, but that was hard to believe. My grandfather’s
portrait hung above the mantelpiece in the drawing room. He wore a
big turban and loose-fitting clothes.

In [59]:
chars=list(set(text))
vocab_size=len(chars)
print(''.join(chars))
print(vocab_size)

hx‘fo1,.DâZAYv…Sbp5WuV– M7t:i2”Nkd“Bc/O—g*s)Pr!R(w_lnHm™'
IK€Qz8"œ6J’90Xjy-qe4F;aGC3?ULTE
91


# Clean the Dataset

-Remove punctuation, digits, and symbols

# Keep only:

- alphabets
- spaces
- newline
- Convert text to lowercase

In [60]:
import re

with open("traindata.txt", "r", encoding="utf-8") as f:
    text = f.read()

# keep alphabets, spaces, and newline
text = re.sub(r"[^A-Za-z\s\n]", " ", text)

# clean extra spaces but keep line structure
text = re.sub(r"[ ]+", " ", text)

# convert to lowercase
text = text.lower()

with open("cleaned.txt", "w", encoding="utf-8") as f:
    f.write(text)

print("cleaning complete")

cleaning complete


# Load Cleaned Dataset

`` Load the processed dataset ``
```Check size and preview text ```

In [61]:
with open("cleaned.txt",'r',encoding='utf-8') as f:
       text2=f.read()

In [62]:
print(f"Lenght of the data set:{len(text2)} ")

Lenght of the data set:201570 


- First 1000 characters

In [63]:
print(text2[:1000])

the portrait of a lady
a photograph
 we re not afraid to die if we
can all be together 
discovering tut the saga
continues
the laburnum top
the voice of the rain
the ailing planet the green
movement s role
childhood
the adventure
silk road
father to son
reprint 
effective reading is receiving from others
their ideas and feelings 
effective reading involves
 understanding the text
 talking about the text
 thinking about language
 working with words
 noticing form and patterns 
reprint 
 the portrait of a lady
khushwant singh
notice these expressions in the text 
infer their meaning from the context 
my grandmother like everybody s grandmother was an old woman 
she had been old and wrinkled for the twenty years that i had known
her people said that she had once been young and pretty and had
even had a husband but that was hard to believe my grandfather s
portrait hung above the mantelpiece in the drawing room he wore a
big turban and loose fitting clothes his long white beard covered the

## Build Character Vocabulary

- Extract unique characters from dataset
- Compute vocabulary size
- chars → unique characters
- vocab_size → number of tokens in dataset

In [64]:
chars2=sorted(list(set(text2)))
vocab_size2=len(chars2)
print(''.join(chars2))
print(vocab_size2)


 abcdefghijklmnopqrstuvwxyz
28


## Encode and Decode Functions
 - Encode text → token IDs
 - Decode token IDs → text

In [65]:
stri = {ch:i for i, ch in enumerate(chars2)}
it = {i:ch for i, ch in enumerate(chars2)}

encode = lambda s: [stri[c] for c in s]# a function that take a string triverse it and return a integer list
decode = lambda l: ''.join([it[i] for i in l])# a function that convert the 

print(encode("eamon"))
print(decode(encode("eamon")))

[6, 2, 14, 16, 15]
eamon


## Convert Dataset to Tensor
- Convert encoded tokens to PyTorch tensor

In [66]:
import torch
data=torch.tensor(encode(text2),dtype=torch.long)
print(data.dtype,data.shape)

torch.int64 torch.Size([201570])


In [67]:
print(data[:1000])

tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1, 16,  7,  1,  2,  1,
        13,  2,  5, 26,  0,  2,  1, 17,  9, 16, 21, 16,  8, 19,  2, 17,  9,  0,
         1, 24,  6,  1, 19,  6,  1, 15, 16, 21,  1,  2,  7, 19,  2, 10,  5,  1,
        21, 16,  1,  5, 10,  6,  1, 10,  7,  1, 24,  6,  0,  4,  2, 15,  1,  2,
        13, 13,  1,  3,  6,  1, 21, 16,  8,  6, 21,  9,  6, 19,  1,  0,  5, 10,
        20,  4, 16, 23,  6, 19, 10, 15,  8,  1, 21, 22, 21,  1, 21,  9,  6,  1,
        20,  2,  8,  2,  0,  4, 16, 15, 21, 10, 15, 22,  6, 20,  0, 21,  9,  6,
         1, 13,  2,  3, 22, 19, 15, 22, 14,  1, 21, 16, 17,  0, 21,  9,  6,  1,
        23, 16, 10,  4,  6,  1, 16,  7,  1, 21,  9,  6,  1, 19,  2, 10, 15,  0,
        21,  9,  6,  1,  2, 10, 13, 10, 15,  8,  1, 17, 13,  2, 15,  6, 21,  1,
        21,  9,  6,  1,  8, 19,  6,  6, 15,  0, 14, 16, 23,  6, 14,  6, 15, 21,
         1, 20,  1, 19, 16, 13,  6,  0,  4,  9, 10, 13,  5,  9, 16, 16,  5,  0,
        21,  9,  6,  1,  2,  5, 23,  6, 

## Train / Validation Split
`` Split dataset to detect overfitting ``
- 90% training
- 10% validation

In [68]:
# now split the data into train data and validation data
n=int(0.9*len(data))
train_data=data[:n]
val_data=data[n:]

In [69]:
block_size=18
train_data[:block_size+1]

tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1, 16,  7,  1,  2,  1,
        13])

In [70]:
a=train_data[:block_size]
b=train_data[1:block_size+1]
for t in range(block_size):
       context=a[:t+1]
       target=b[t]
       print(f"Input:{context},target:{target}")

Input:tensor([21]),target:9
Input:tensor([21,  9]),target:6
Input:tensor([21,  9,  6]),target:1
Input:tensor([21,  9,  6,  1]),target:17
Input:tensor([21,  9,  6,  1, 17]),target:16
Input:tensor([21,  9,  6,  1, 17, 16]),target:19
Input:tensor([21,  9,  6,  1, 17, 16, 19]),target:21
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21]),target:19
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19]),target:2
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2]),target:10
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10]),target:21
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21]),target:1
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1]),target:16
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1, 16]),target:7
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1, 16,  7]),target:1
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1, 16,  7,  1]),target:2
Input:tensor([21,  9,  6,  1, 17, 16, 19, 21, 19,  2, 10, 21,  1

- Context and Target Example
- Demonstrate next-token prediction

In [71]:
batch_size=4
block_size=18
torch.manual_seed(1337)
def get_batch(split):
       if split=='train':
              data=train_data
       else:
              data=val_data
       ix = torch.randint(len(data) - block_size, (batch_size,))
       x=torch.stack([data[i:i+block_size]for i in ix])
       y=torch.stack([data[i+1:i+block_size+1]for i in ix])
       return x,y

xb,yb=get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)
print("--------------------------------------")

for b in range(batch_size):
       for t in range(block_size):
              context=xb[b,:t+1]
              target=yb[b,t]
              print(f"context:{context} and target:{target} ")


inputs:
torch.Size([4, 18])
tensor([[ 2, 13,  6, 15, 21, 20,  1, 10, 15,  1, 21,  9,  6, 10, 19,  1, 13,  2],
        [ 1, 24,  2, 20,  1,  2,  1,  3, 16, 26,  1, 24,  9, 16,  1, 13, 16, 23],
        [ 1, 14,  2, 11, 16, 19,  1, 20,  2, 17, 21,  2, 19, 10, 20,  9, 10,  1],
        [ 8, 19, 16, 22, 15,  5,  1,  0,  0, 20, 22,  5,  5,  6, 15, 13, 26,  1]])
targets:
torch.Size([4, 18])
tensor([[13,  6, 15, 21, 20,  1, 10, 15,  1, 21,  9,  6, 10, 19,  1, 13,  2, 15],
        [24,  2, 20,  1,  2,  1,  3, 16, 26,  1, 24,  9, 16,  1, 13, 16, 23,  6],
        [14,  2, 11, 16, 19,  1, 20,  2, 17, 21,  2, 19, 10, 20,  9, 10,  1, 14],
        [19, 16, 22, 15,  5,  1,  0,  0, 20, 22,  5,  5,  6, 15, 13, 26,  1,  2]])
--------------------------------------
context:tensor([2]) and target:13 
context:tensor([ 2, 13]) and target:6 
context:tensor([ 2, 13,  6]) and target:15 
context:tensor([ 2, 13,  6, 15]) and target:21 
context:tensor([ 2, 13,  6, 15, 21]) and target:20 
context:tensor([ 2, 13,  6, 

### Bigram Language Model
- Predict next character based only on current character
- Uses embedding lookup

In [92]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size2)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([576, 28])
tensor(4.0288, grad_fn=<NllLossBackward0>)

o gczsr
iwsmm bjn rn xctpzdcyyhvnty
n xawrhmsfrcywkkmrqkpdxjufpglkprzot
gu
u
jnqectluy
kzr
qkpwoyr
j


In [73]:
# Adding a Py torch optimizer 
optimizer=torch.optim.AdamW(m.parameters(),lr=1e-3)

In [74]:
# Training loop
batch_size=32
for steps in range(10000):
       xb,yb=get_batch('train')
       logits,loss=m(xb,yb)
       optimizer.zero_grad(set_to_none=None)
       loss.backward()
       optimizer.step()

print(loss.item())

2.235884189605713


In [75]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=1000)[0].tolist()))



 andordely 
he min jnd as ter butornn oouate
aw thed thef y bolerthent t hin meras apppy win we furanwnd y te nd ascasande a wand it fly stoulaksaver 

th 
tittwitht t opal s homexpareplitee lwhee o o acy hetaiad he po a g ge oknof ho ad s ckndy so athace se sk allear p arem glean theng pe whedo surker r wha alaild b an sa heerimmpad the fus d hed 
 tole mus add hthadry s hndise jauthigsaty en sk s vt beendago d le omowoale dst whreeabe imis avellaind a ck y 

te we has cere tl meathelath ad rout d ane tsofi hthend s ay tism asm cond andy ffry be g t be he n tatu hondanef se waicerimogasomuso oovas thepor ardend fo abrth larihethn jarckin angan
 heowhel iguo goooocentst m helang ck athe painthe t shed tld a t lathist
 te oo ariny f sed r sin 
t aplanely d tocivesolle inshoyiso agurbupos anheny led wasazered thive t ben bsore id hthecandliriskqustit owineway ieline y wacongand inly oerlit ler berisofese th f d ge ing adn adar jul 
mun ife aire 

ds authakstste lle

noy o atay tt n ti 

# MATHS in Self attention

In [76]:
torch.manual_seed(42)
s = torch.tril(torch.ones(3, 3))
s = s / torch.sum(s, 1, keepdim=True)
d = torch.randint(0,10,(3,2)).float()
c = s @ d
print('s=')
print(s)
print('--')
print('d=')
print(d)
print('--')
print('c=')
print(c)

s=
tensor([[1.0000, 0.0000, 0.0000],
        [0.5000, 0.5000, 0.0000],
        [0.3333, 0.3333, 0.3333]])
--
d=
tensor([[2., 7.],
        [6., 4.],
        [6., 5.]])
--
c=
tensor([[2.0000, 7.0000],
        [4.0000, 5.5000],
        [4.6667, 5.3333]])


In [77]:
torch.manual_seed(1337)
B,T,C = 4,8,2 # batch, time, channels
x = torch.randn(B,T,C)
x.shape

torch.Size([4, 8, 2])

In [78]:
# Aim: x[b,t] = mean_{i<=t} x[b,i]
#option 1
xbow = torch.zeros((B,T,C))
for b in range(B):
    for t in range(T):
        xprev = x[b,:t+1] # (t,C)
        xbow[b,t] = torch.mean(xprev, 0)


In [79]:
# option 2: using matrix multiply for a weighted aggregation
wei = torch.tril(torch.ones(T, T))
wei = wei / wei.sum(1, keepdim=True)
xbow2 = wei @ x # (B, T, T) @ (B, T, C) ----> (B, T, C)
torch.allclose(xbow, xbow2)

False

In [80]:
# option 3: using Softmax
tril = torch.tril(torch.ones(T, T))
wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)
xbow3 = wei @ x
torch.allclose(xbow, xbow3)


False

In [81]:
# option 4 : self attention

torch.manual_seed(1337)
B,T,C = 4,8,32 # batch, time, channels
x = torch.randn(B,T,C)

# let's see a single Head perform self-attention
head_size = 16
key = nn.Linear(C, head_size, bias=False)
query = nn.Linear(C, head_size, bias=False)
value = nn.Linear(C, head_size, bias=False)
k = key(x)   # (B, T, 16)
q = query(x) # (B, T, 16)
wei =  q @ k.transpose(-2, -1) # (B, T, 16) @ (B, 16, T) ---> (B, T, T)

tril = torch.tril(torch.ones(T, T))
#wei = torch.zeros((T,T))
wei = wei.masked_fill(tril == 0, float('-inf'))
wei = F.softmax(wei, dim=-1)

v = value(x)
out = wei @ v
#out = wei @ x

out.shape

torch.Size([4, 8, 16])

In [82]:
wei[0]

tensor([[1.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.1574, 0.8426, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.2088, 0.1646, 0.6266, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.5792, 0.1187, 0.1889, 0.1131, 0.0000, 0.0000, 0.0000, 0.0000],
        [0.0294, 0.1052, 0.0469, 0.0276, 0.7909, 0.0000, 0.0000, 0.0000],
        [0.0176, 0.2689, 0.0215, 0.0089, 0.6812, 0.0019, 0.0000, 0.0000],
        [0.1691, 0.4066, 0.0438, 0.0416, 0.1048, 0.2012, 0.0329, 0.0000],
        [0.0210, 0.0843, 0.0555, 0.2297, 0.0573, 0.0709, 0.2423, 0.2391]],
       grad_fn=<SelectBackward0>)

In [83]:
k = torch.randn(B,T,head_size)
q = torch.randn(B,T,head_size)
wei = q @ k.transpose(-2, -1) * head_size**-0.5
k.var()

tensor(1.0449)

In [84]:
q.var()

tensor(1.0700)

In [85]:
wei.var()

tensor(1.0918)

In [86]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5]), dim=-1)

tensor([0.1925, 0.1426, 0.2351, 0.1426, 0.2872])

In [87]:
torch.softmax(torch.tensor([0.1, -0.2, 0.3, -0.2, 0.5])*8, dim=-1)

tensor([0.0326, 0.0030, 0.1615, 0.0030, 0.8000])

In [88]:
class LayerNorm1d: # (used to be BatchNorm1d)

  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)

  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out

  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [89]:
#mean
x[:,0].mean(), x[:,0].std() 

(tensor(0.1469), tensor(0.8803))

In [90]:
x[0,:].mean(), x[0,:].std() 

(tensor(-9.5367e-09), tensor(1.0000))